//! Domain models and configuration types

use serde::{Deserialize, Serialize};
use time::OffsetDateTime;

// === Configuration ===

#[derive(Debug, Clone, Deserialize)]
pub struct AppConfig {
    pub server: ServerConfig,
    pub storage: StorageConfig,
    pub services: ServicesConfig,
}

#[derive(Debug, Clone, Deserialize)]
pub struct ServerConfig {
    pub bind_address: String,
    pub port: u16,
}

#[derive(Debug, Clone, Deserialize)]
pub struct StorageConfig {
    pub sqlite_path: String,
    pub assets_root: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct ServicesConfig {
    pub llm: LlmServices,
    pub avatar: AvatarServices,
    pub tts: TtsServices,
    pub mcp: McpServices,
}

#[derive(Debug, Clone, Deserialize)]
pub struct LlmServices {
    pub cloud_primary: String,
    pub local_ollama: String,
    pub local_llamacpp: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct AvatarServices {
    pub image_to_video: String,
    pub lip_sync: String,
    pub background_removal: String,
    pub video_stretch: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct TtsServices {
    pub primary: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct McpServices {
    pub playwright_hub: String,
}

// === Domain Models ===

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Project {
    pub id: Option<i64>,
    pub slug: String,
    pub title: String,
    pub subtitle: Option<String>,
    pub description: Option<String>,
    pub created_at: OffsetDateTime,
    pub updated_at: OffsetDateTime,
}

impl Project {
    pub fn new(slug: String, title: String) -> Self {
        let now = OffsetDateTime::now_utc();
        Self {
            id: None,
            slug,
            title,
            subtitle: None,
            description: None,
            created_at: now,
            updated_at: now,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Scene {
    pub id: Option<i64>,
    pub project_id: i64,
    pub title: String,
    pub description: Option<String>,
    pub sort_order: i32,
    pub script_text: Option<String>,
    pub created_at: OffsetDateTime,
    pub updated_at: OffsetDateTime,
}

impl Scene {
    pub fn new(project_id: i64, title: String, sort_order: i32) -> Self {
        let now = OffsetDateTime::now_utc();
        Self {
            id: None,
            project_id,
            title,
            description: None,
            sort_order,
            script_text: None,
            created_at: now,
            updated_at: now,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Asset {
    pub id: Option<i64>,
    pub project_id: i64,
    pub scene_id: Option<i64>,
    pub name: String,
    pub asset_type: String,
    pub file_path: Option<String>,
    pub url: Option<String>,
    pub metadata: Option<String>,
    pub created_at: OffsetDateTime,
    pub updated_at: OffsetDateTime,
}

impl Asset {
    pub fn new(
        project_id: i64,
        scene_id: Option<i64>,
        name: String,
        asset_type: String,
        file_path: Option<String>,
        url: Option<String>,
        metadata: Option<String>,
    ) -> Self {
        let now = OffsetDateTime::now_utc();
        Self {
            id: None,
            project_id,
            scene_id,
            name,
            asset_type,
            file_path,
            url,
            metadata,
            created_at: now,
            updated_at: now,
        }
    }
}

/// Target specification for MCP/Playwright screen capture
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SceneTarget {
    pub url: String,
    pub actions: Vec<SceneAction>,
    pub width: u32,
    pub height: u32,
}

/// Actions to perform during scene capture
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum SceneAction {
    Click { selector: String },
    Type { selector: String, text: String },
    Wait { duration_ms: u64 },
    Screenshot,
}

/// A scene generated by the LLM (before persistence)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedScene {
    pub order: i32,
    pub title: String,
    pub script_text: String,
    pub description: Option<String>,
    pub overlay_text: Option<String>,
}

/// Response from LLM script generation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedScript {
    pub scenes: Vec<GeneratedScene>,
}
